const DATA=window.STUDY_DATA,state=loadState();let mode="",items=[],index=0,score=0,answered=false,revealed=false;
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),shuffle=a=>[...a].sort(()=>Math.random()-.5);
function save(){saveState(state)}
function pool(m){return m==="vocab"?DATA.vocab.concat(state.customVocab):m==="phrases"?DATA.phrases.concat(state.customPhrases):DATA.questions}
function home(){app.innerHTML=`<main class="wrap"><section class="hero"><h1>Vietnamese Driving Practice</h1><p>Study your vocabulary, exam phrases, and driving-test questions.</p></section><div class="grid"><section class="card"><h2>🌱 Vocabulary</h2><p>Vietnamese → English.</p><button class="primary" data-a="start" data-m="vocab">Start</button></section><section class="card"><h2>🧩 Exam Phrases</h2><p>Recurring expressions.</p><button class="primary" data-a="start" data-m="phrases">Start</button></section><section class="card"><h2>🚦 Driving Test</h2><p>Practice the 250-question bank.</p><button class="primary" data-a="start" data-m="questions">Start</button></section></div><section class="card management"><h2>📚 Word & Phrase Banks</h2><p>Add, edit, or delete material whenever you want.</p><button class="secondary" data-a="manage">Open Banks</button></section><section class="card settings"><h2>⚙️ Practice Settings</h2><div class="setting-grid"><label>Vocabulary<select data-setting="vocabMode"><option value="choice" ${state.settings.vocabMode==="choice"?"selected":""}>Multiple choice</option><option value="recall" ${state.settings.vocabMode==="recall"?"selected":""}>Recall + reveal</option></select></label><label>Phrase<select data-setting="phraseMode"><option value="choice" ${state.settings.phraseMode==="choice"?"selected":""}>Multiple choice</option><option value="recall" ${state.settings.phraseMode==="recall"?"selected":""}>Recall + reveal</option></select></label><label>Choices<select data-setting="choices">${[3,4,5,6].map(n=>`<option value="${n}" ${state.settings.choices===n?"selected":""}>${n} answers</option>`).join("")}</select></label></div></section><p class="completed">Questions completed: <b>${state.completed}</b></p></main>`}
function choices(x){let c=String(x.Back||"").trim(),d=DATA.vocab.concat(DATA.phrases,state.customVocab,state.customPhrases).map(y=>String(y.Back||"").trim()).filter(y=>y&&y!==c);return shuffle([c,...shuffle([...new Set(d)]).slice(0,state.settings.choices-1)])}
function start(m){mode=m;index=0;score=0;answered=false;revealed=false;items=shuffle(pool(m)).slice(0,m==="vocab"?10:m==="phrases"?5:10);show()}
function show(){let x=items[index],title=mode==="vocab"?"🌱 Vocabulary":mode==="phrases"?"🧩 Exam Phrases":"🚦 Driving Test";let recall=(mode==="vocab"&&state.settings.vocabMode==="recall")||(mode==="phrases"&&state.settings.phraseMode==="recall"),body;if(mode==="questions")body=`<section class="prompt"><div class="num">Question ${esc(x.num)}</div><div class="vi">${esc(x.vi)}</div></section><div class="answers">${x.options.map((o,n)=>`<button class="answer" data-q="${n}">${n+1}. ${esc(o)}</button>`).join("")}</div>`;else if(recall)body=`<section class="prompt recall"><div class="recall-label">What does this mean?</div><div class="vi">${esc(x.Front)}</div></section><div id="recall">${revealed?`<div class="revealed"><small>Answer</small><div>${esc(x.Back)}</div></div><p class="how">How did you do?</p><button class="grade good" data-a="grade" data-ok="1">✓ I knew it</button><button class="grade bad" data-a="grade" data-ok="0">✗ I didn't know it</button>`:`<button class="primary reveal" data-a="reveal">Reveal Answer</button>`}</div>`;else body=`<section class="prompt"><div class="vi">${esc(x.Front)}</div></section><div class="answers">${choices(x).map(c=>`<button class="answer" data-e="${esc(c)}">${esc(c)}</button>`).join("")}</div>`;app.innerHTML=`<main class="wrap lesson"><div class="head"><span>${title}</span><span>${index+1} / ${items.length}</span></div><div class="progress"><span style="width:${index/items.length*100}%"></span></div>${body}<div id="fb"></div><button class="secondary" data-a="home">Exit</button></main>`}
function answer(b){if(answered)return;answered=true;let x=items[index],bs=[...document.querySelectorAll(".answer")],ok;if(mode==="questions"){let n=+b.dataset.q;ok=n===x.correct;bs[x.correct]?.classList.add("correct");if(!ok){b.classList.add("wrong");showfb(false,`✗ Not quite.<br><b>Correct:</b> ${x.correct+1}. ${esc(x.options[x.correct])}<div class="translation">${esc(x.en||"")}</div>`)}else showfb(true,"✓ Correct!")}else{let c=String(x.Back||"").trim();ok=b.dataset.e===c;bs.find(z=>z.dataset.e===c)?.classList.add("correct");if(!ok){b.classList.add("wrong");showfb(false,`✗ Not quite.<br><b>Correct:</b> ${esc(c)}`)}else showfb(true,"✓ Correct!")}bs.forEach(z=>z.classList.add("locked"));if(ok){score++;state.completed++;save()}}
function showfb(ok,msg){fb.innerHTML=`<div class="feedback ${ok?"ok":"bad"}">${msg}</div><button class="primary continue" data-a="next">Continue</button>`}
function reveal(){revealed=true;show()}
function grade(ok){if(answered)return;answered=true;if(ok){score++;state.completed++;save()}fb.innerHTML=`<div class="feedback ${ok?"ok":"bad"}">${ok?"✓ Nice!":"Keep working on this one."}</div><button class="primary continue" data-a="next">Continue</button>`}
function next(){if(index+1<items.length){index++;answered=false;revealed=false;show()}else app.innerHTML=`<main class="wrap lesson"><section class="result"><div class="result-icon">${score===items.length?"🏆":"✓"}</div><h1>Lesson complete</h1><p>You got <b>${score} / ${items.length}</b> correct.</p><button class="primary" data-a="home">Back to home</button></section></main>`}
function parseCSV(text){let rows=[],row=[],field="",quoted=false;for(let i=0;i<text.length;i++){let ch=text[i];if(quoted){if(ch==='"'){if(text[i+1]==='"'){field+='"';i++}else quoted=false}else field+=ch}else{if(ch==='"'&&field===''){quoted=true}else if(ch===','){row.push(field);field=""}else if(ch==='\n'){row.push(field);if(row.some(v=>v.trim()!==''))rows.push(row);row=[];field=""}else if(ch==='\r'){if(text[i+1]==='\n')i++;row.push(field);if(row.some(v=>v.trim()!==''))rows.push(row);row=[];field=""}else field+=ch}}if(quoted)throw new Error("Unclosed quote in CSV.");row.push(field);if(row.some(v=>v.trim()!==''))rows.push(row);return rows}
function manager(){let list=(a,p)=>a.length?a.map((x,n)=>`<div class="row"><div><b>${esc(x.Front)}</b> → ${esc(x.Back)}</div><div class="actions"><button class="small" data-a="edit" data-p="${p}" data-i="${n}">Edit</button><button class="small danger" data-a="del" data-p="${p}" data-i="${n}">Delete</button></div></div>`).join(""):"<p>No custom items yet.</p>";app.innerHTML=`<main class="wrap"><section class="hero"><h1>📚 Word & Phrase Banks</h1><p>Your custom items are saved on this device and immediately enter future lessons.</p></section><section class="card"><h2>Paste vocabulary in bulk</h2><p>Paste CSV text with one Vietnamese/English pair per line. Example: <code>"nhường đường","to give way"</code></p><textarea id="bulkCsv" class="bulk-csv" rows="8" placeholder='"Câu ...","Question ..."
"... nào dưới đây?","which ... below?"'></textarea><button class="primary" data-a="bulkAdd">Add all to Word Bank</button></section><section class="card"><h2>Add new item</h2><div class="form"><label>Vietnamese<input id="vi" placeholder="nhường đường"></label><label>English<input id="en" placeholder="to give way"></label><label>Bank<select id="which"><option value="vocab">Word Bank</option><option value="phrases">Phrase Bank</option></select></label></div><button class="primary" data-a="add">Add</button><button class="secondary" data-a="home">Back</button></section><section class="card bank"><h2>Custom Word Bank (${state.customVocab.length})</h2>${list(state.customVocab,"vocab")}</section><section class="card bank"><h2>Custom Phrase Bank (${state.customPhrases.length})</h2>${list(state.customPhrases,"phrases")}</section></main>`}
function add(){let vi=$("#vi").value.trim(),en=$("#en").value.trim(),p=$("#which").value;if(!vi||!en)return alert("Enter both Vietnamese and English.");(p==="vocab"?state.customVocab:state.customPhrases).push({Front:vi,Back:en});save();manager()}
function bulkAdd(){let text=$("#bulkCsv").value.trim();if(!text)return alert("Paste your CSV text first.");try{let rows=parseCSV(text);let start=0;if(rows.length&&rows[0].length>=2&&/^(vietnamese|front|word)$/i.test(rows[0][0].trim())&&/^(english|back|translation)$/i.test(rows[0][1].trim()))start=1;let added=0;for(let i=start;i<rows.length;i++){let vi=String(rows[i][0]??"").trim(),en=String(rows[i][1]??"").trim();if(!vi&&!en)continue;if(!vi||!en)continue;state.customVocab.push({Front:vi,Back:en});added++}if(!added)return alert("No valid Vietnamese/English pairs were found.");save();alert(`Added ${added} item${added===1?"":"s"} to the Word Bank.`);manager()}catch(err){alert("Could not read the CSV. Make sure each line contains two quoted fields, like: \"Vietnamese\",\"English\".")}}
function edit(p,n){let a=p==="vocab"?state.customVocab:state.customPhrases,x=a[n],vi=prompt("Vietnamese:",x.Front);if(vi===null)return;let en=prompt("English:",x.Back);if(en===null)return;if(!vi.trim()||!en.trim())return alert("Both fields are required.");a[n]={Front:vi.trim(),Back:en.trim()};save();manager()}
function del(p,n){if(!confirm("Delete this item?"))return;(p==="vocab"?state.customVocab:state.customPhrases).splice(n,1);save();manager()}
document.addEventListener("change",e=>{let k=e.target.dataset.setting;if(k){state.settings[k]=k==="choices"?+e.target.value:e.target.value;save()}})
document.addEventListener("click",e=>{let b=e.target.closest(".answer");if(b){answer(b);return}let a=e.target.closest("[data-a]");if(!a)return;switch(a.dataset.a){case"start":start(a.dataset.m);break;case"home":home();break;case"manage":manager();break;case"add":add();break;case"bulkAdd":bulkAdd();break;case"edit":edit(a.dataset.p,+a.dataset.i);break;case"del":del(a.dataset.p,+a.dataset.i);break;case"reveal":reveal();break;case"grade":grade(a.dataset.ok==="1");break;case"next":next();break}});home();
