const DATA=window.STUDY_DATA,state=loadState();let mode="",items=[],index=0,score=0,answered=false,revealed=false;
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),shuffle=a=>[...a].sort(()=>Math.random()-.5);
function save(){saveState(state)}
function pool(m){return m==="vocab"?DATA.vocab.concat(state.customVocab):m==="phrases"?DATA.phrases.concat(state.customPhrases):DATA.questions}
function csvEscape(v){v=String(v??"");return '"'+v.replace(/"/g,'""')+'"'}
function exportCsv(){
  const rows=[['Bank','Vietnamese','English'],...state.customVocab.map(x=>['Word',x.Front,x.Back]),...state.customPhrases.map(x=>['Phrase',x.Front,x.Back])];
  const csv='\ufeff'+rows.map(r=>r.map(csvEscape).join(',')).join('\r\n');
  const filename='vietnamese-driving-word-bank.csv';
  if(window.Android?.saveCsv){window.Android.saveCsv(filename,csv);return}
  const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
function importCsv(){document.getElementById('csvInput')?.click()}
function parseCsv(text){
  text=text.replace(/^\ufeff/,'');let rows=[],row=[],cell='',quoted=false;
  for(let i=0;i<text.length;i++){let ch=text[i],next=text[i+1];if(quoted){if(ch==='"'&&next==='"'){cell+='"';i++}else if(ch==='"'){quoted=false}else cell+=ch}else{if(ch==='"'){quoted=true}else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=ch}}row.push(cell);if(row.length>1||row[0])rows.push(row);return rows}
function handleImport(file){
  if(!file)return;const reader=new FileReader();reader.onload=()=>{try{
    const rows=parseCsv(String(reader.result));if(rows.length<2)throw new Error('The CSV contains no data.');
    const header=rows[0].map(x=>x.trim().toLowerCase());let bi=header.indexOf('bank'),vi=header.indexOf('vietnamese'),ei=header.indexOf('english');
    if(vi<0||ei<0)throw new Error('CSV must contain Vietnamese and English columns.');
    let vocab=[],phrases=[];
    rows.slice(1).forEach(r=>{const front=(r[vi]??'').trim(),back=(r[ei]??'').trim(),bank=(bi>=0?(r[bi]??''):'Word').trim().toLowerCase();if(!front&&!back)return;if(!front||!back)throw new Error('Every item must have both Vietnamese and English text.');const item={Front:front,Back:back};if(bank==='phrase'||bank==='phrases')phrases.push(item);else vocab.push(item)});
    if(!confirm(`Replace the current custom banks with ${vocab.length} words and ${phrases.length} phrases?\n\nThis cannot be undone unless you have an export backup.`))return;
    state.customVocab=vocab;state.customPhrases=phrases;save();manager();alert(`Imported ${vocab.length} words and ${phrases.length} phrases.`)
  }catch(err){alert('Import failed: '+err.message)}};reader.readAsText(file)}
function home(){app.innerHTML=`<main class="wrap"><section class="hero"><h1>Vietnamese Driving Practice</h1><p>Study your vocabulary, exam phrases, and driving-test questions.</p></section><div class="grid"><section class="card"><h2>🌱 Vocabulary</h2><p>Vietnamese → English.</p><button class="primary" data-a="start" data-m="vocab">Start</button></section><section class="card"><h2>🧩 Exam Phrases</h2><p>Recurring expressions.</p><button class="primary" data-a="start" data-m="phrases">Start</button></section><section class="card"><h2>🚦 Driving Test</h2><p>Practice the 250-question bank.</p><button class="primary" data-a="start" data-m="questions">Start</button></section></div><section class="card management"><h2>📚 Word & Phrase Banks</h2><p>Add, edit, or delete material whenever you want.</p><button class="secondary" data-a="manage">Open Banks</button></section><section class="card settings"><h2>⚙️ Practice Settings</h2><div class="setting-grid"><label>Vocabulary<select data-setting="vocabMode"><option value="choice" ${state.settings.vocabMode==="choice"?"selected":""}>Multiple choice</option><option value="recall" ${state.settings.vocabMode==="recall"?"selected":""}>Recall + reveal</option></select></label><label>Phrase<select data-setting="phraseMode"><option value="choice" ${state.settings.phraseMode==="choice"?"selected":""}>Multiple choice</option><option value="recall" ${state.settings.phraseMode==="recall"?"selected":""}>Recall + reveal</option></select></label><label>Choices<select data-setting="choices">${[3,4,5,6].map(n=>`<option value="${n}" ${state.settings.choices===n?"selected":""}>${n} answers</option>`).join("")}</select></label></div></section><p class="completed">Questions completed: <b>${state.completed}</b></p></main>`}
function choices(x){let c=String(x.Back||"").trim(),d=DATA.vocab.concat(DATA.phrases,state.customVocab,state.customPhrases).map(y=>String(y.Back||"").trim()).filter(y=>y&&y!==c);return shuffle([c,...shuffle([...new Set(d)]).slice(0,state.settings.choices-1)])}
function start(m){mode=m;index=0;score=0;answered=false;revealed=false;items=shuffle(pool(m)).slice(0,m==="vocab"?10:m==="phrases"?5:10);show()}
function show(){let x=items[index],title=mode==="vocab"?"🌱 Vocabulary":mode==="phrases"?"🧩 Exam Phrases":"🚦 Driving Test";let recall=(mode==="vocab"&&state.settings.vocabMode==="recall")||(mode==="phrases"&&state.settings.phraseMode==="recall"),body;if(mode==="questions")body=`<section class="prompt"><div class="num">Question ${esc(x.num)}</div><div class="vi">${esc(x.vi)}</div></section><div class="answers">${x.options.map((o,n)=>`<button class="answer" data-q="${n}">${n+1}. ${esc(o)}</button>`).join("")}</div>`;else if(recall)body=`<section class="prompt recall"><div class="recall-label">What does this mean?</div><div class="vi">${esc(x.Front)}</div></section><div id="recall">${revealed?`<div class="revealed"><small>Answer</small><div>${esc(x.Back)}</div></div><p class="how">How did you do?</p><button class="grade good" data-a="grade" data-ok="1">✓ I knew it</button><button class="grade bad" data-a="grade" data-ok="0">✗ I didn't know it</button>`:`<button class="primary reveal" data-a="reveal">Reveal Answer</button>`}</div>`;else body=`<section class="prompt"><div class="vi">${esc(x.Front)}</div></section><div class="answers">${choices(x).map(c=>`<button class="answer" data-e="${esc(c)}">${esc(c)}</button>`).join("")}</div>`;app.innerHTML=`<main class="wrap lesson"><div class="head"><span>${title}</span><span>${index+1} / ${items.length}</span></div><div class="progress"><span style="width:${index/items.length*100}%"></span></div>${body}<div id="fb"></div><button class="secondary" data-a="home">Exit</button></main>`}
function answer(b){if(answered)return;answered=true;let x=items[index],bs=[...document.querySelectorAll(".answer")],ok;if(mode==="questions"){let n=+b.dataset.q;ok=n===x.correct;bs[x.correct]?.classList.add("correct");if(!ok){b.classList.add("wrong");showfb(false,`✗ Not quite.<br><b>Correct:</b> ${x.correct+1}. ${esc(x.options[x.correct])}<div class="translation">${esc(x.en||"")}</div>`)}else showfb(true,"✓ Correct!")}else{let c=String(x.Back||"").trim();ok=b.dataset.e===c;bs.find(z=>z.dataset.e===c)?.classList.add("correct");if(!ok){b.classList.add("wrong");showfb(false,`✗ Not quite.<br><b>Correct:</b> ${esc(c)}`)}else showfb(true,"✓ Correct!")}bs.forEach(z=>z.classList.add("locked"));if(ok){score++;state.completed++;save()}}
function showfb(ok,msg){fb.innerHTML=`<div class="feedback ${ok?"ok":"bad"}">${msg}</div><button class="primary continue" data-a="next">Continue</button>`}
function reveal(){revealed=true;show()}
function grade(ok){if(answered)return;answered=true;if(ok){score++;state.completed++;save()}fb.innerHTML=`<div class="feedback ${ok?"ok":"bad"}">${ok?"✓ Nice!":"Keep working on this one."}</div><button class="primary continue" data-a="next">Continue</button>`}
function next(){if(index+1<items.length){index++;answered=false;revealed=false;show()}else app.innerHTML=`<main class="wrap lesson"><section class="result"><div class="result-icon">${score===items.length?"🏆":"✓"}</div><h1>Lesson complete</h1><p>You got <b>${score} / ${items.length}</b> correct.</p><button class="primary" data-a="home">Back to home</button></section></main>`}
function manager(){let list=(a,p)=>a.length?a.map((x,n)=>`<div class="row"><div><b>${esc(x.Front)}</b> → ${esc(x.Back)}</div><div class="actions"><button class="small" data-a="edit" data-p="${p}" data-i="${n}">Edit</button><button class="small danger" data-a="del" data-p="${p}" data-i="${n}">Delete</button></div></div>`).join(""):"<p>No custom items yet.</p>";app.innerHTML=`<main class="wrap"><section class="hero"><h1>📚 Word & Phrase Banks</h1><p>Your custom items are saved on this device and immediately enter future lessons.</p></section><section class="card"><h2>Add new item</h2><div class="form"><label>Vietnamese<input id="vi" placeholder="nhường đường"></label><label>English<input id="en" placeholder="to give way"></label><label>Bank<select id="which"><option value="vocab">Word Bank</option><option value="phrases">Phrase Bank</option></select></label></div><button class="primary" data-a="add">Add</button><button class="secondary" data-a="home">Back</button></section><section class="card backup"><h2>💾 Export / Import</h2><p>Export both custom banks to one CSV file, or import a CSV to completely replace both custom banks.</p><input id="csvInput" type="file" accept=".csv,text/csv" hidden><button class="primary" data-a="export">Export Word Bank (.csv)</button><button class="secondary" data-a="import">Import CSV (replace everything)</button><p class="hint">CSV columns: <b>Bank</b>, <b>Vietnamese</b>, <b>English</b>. Use <b>Word</b> or <b>Phrase</b> in the Bank column.</p></section><section class="card bank"><h2>Custom Word Bank (${state.customVocab.length})</h2>${list(state.customVocab,"vocab")}</section><section class="card bank"><h2>Custom Phrase Bank (${state.customPhrases.length})</h2>${list(state.customPhrases,"phrases")}</section></main>`}
function add(){let vi=$("#vi").value.trim(),en=$("#en").value.trim(),p=$("#which").value;if(!vi||!en)return alert("Enter both Vietnamese and English.");(p==="vocab"?state.customVocab:state.customPhrases).push({Front:vi,Back:en});save();manager()}
function edit(p,n){let a=p==="vocab"?state.customVocab:state.customPhrases,x=a[n],vi=prompt("Vietnamese:",x.Front);if(vi===null)return;let en=prompt("English:",x.Back);if(en===null)return;if(!vi.trim()||!en.trim())return alert("Both fields are required.");a[n]={Front:vi.trim(),Back:en.trim()};save();manager()}
function del(p,n){if(!confirm("Delete this item?"))return;(p==="vocab"?state.customVocab:state.customPhrases).splice(n,1);save();manager()}
document.addEventListener("change",e=>{let k=e.target.dataset.setting;if(k){state.settings[k]=k==="choices"?+e.target.value:e.target.value;save()}})
document.addEventListener("change",e=>{if(e.target.id==="csvInput"){handleImport(e.target.files[0]);e.target.value=""}})
document.addEventListener("click",e=>{let b=e.target.closest(".answer");if(b){answer(b);return}let a=e.target.closest("[data-a]");if(!a)return;switch(a.dataset.a){case"start":start(a.dataset.m);break;case"home":home();break;case"manage":manager();break;case"add":add();break;case"export":exportCsv();break;case"import":importCsv();break;case"edit":edit(a.dataset.p,+a.dataset.i);break;case"del":del(a.dataset.p,+a.dataset.i);break;case"reveal":reveal();break;case"grade":grade(a.dataset.ok==="1");break;case"next":next();break}});home();
